"""
The choices made in the Settings app (settings.py), kept in
~/.config/hypr/user-settings.json and turned into ~/.config/hypr/user-settings.lua,
which hyprland.lua loads last, so they win over its defaults. Writing the Lua file
makes Hyprland reload by itself.

    import settings_store as store
    s = store.load()                  # every setting, defaults filled in
    store.save(dict(s, gaps=False))   # raises ValueError for a value Hyprland can't take
"""

import json
import os
import re

CONFIG = os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config"))
XKB_SYMBOLS = "/usr/share/X11/xkb/symbols"

DEFAULTS = dict(kb_layout="us,ir", natural_scroll=True, tap_to_click=True, gaps=True, animations=True)
SWITCHES = ("natural_scroll", "tap_to_click", "gaps", "animations")
# the values hyprland.lua uses (and toggle-gaps.sh puts back)
GAPS_ON = dict(gaps_in=10, gaps_out=20, rounding=10)


def paths(config=CONFIG):
    hypr = os.path.join(config, "hypr")
    return os.path.join(hypr, "user-settings.json"), os.path.join(hypr, "user-settings.lua")


def known_layouts(symbols=XKB_SYMBOLS):
    """Keyboard layouts this system has, or None if it can't tell."""
    try:
        return set(os.listdir(symbols))
    except OSError:
        return None


def check_layouts(value, symbols=XKB_SYMBOLS):
    """ "us, ir" -> "us,ir". A layout the system doesn't have would leave you without a
    working keyboard, so it is refused."""
    parts = [p.strip().lower() for p in str(value).split(",") if p.strip()]
    if not parts or len(parts) > 4:
        raise ValueError("Give one to four keyboard layouts, like: us,ir")
    known = known_layouts(symbols)
    for p in parts:
        if not re.fullmatch(r"[a-z]{2,8}", p) or (known is not None and p not in known):
            raise ValueError(f"“{p}” is not a keyboard layout on this system (examples: us, ir, de, fr)")
    return ",".join(parts)


def load(config=CONFIG):
    json_path, _ = paths(config)
    try:
        with open(json_path) as f:
            saved = json.load(f)
    except (OSError, ValueError):
        saved = {}
    s = dict(DEFAULTS)
    if isinstance(saved, dict):
        s.update({k: v for k, v in saved.items() if k in DEFAULTS and type(v) is type(DEFAULTS[k])})
    return s


def to_lua(s):
    """The Lua that applies these settings over hyprland.lua's defaults."""
    gaps = GAPS_ON if s["gaps"] else dict(gaps_in=0, gaps_out=0, rounding=0)
    b = lambda v: "true" if v else "false"  # noqa: E731
    return (
        "-- generated by the Settings app (SUPER+I) from user-settings.json: edits here are lost\n"
        "hl.config({\n"
        f"    input = {{ kb_layout = {json.dumps(s['kb_layout'])},\n"
        f"              touchpad = {{ natural_scroll = {b(s['natural_scroll'])},"
        f" tap_to_click = {b(s['tap_to_click'])} }} }},\n"
        f"    general = {{ gaps_in = {gaps['gaps_in']}, gaps_out = {gaps['gaps_out']} }},\n"
        f"    decoration = {{ rounding = {gaps['rounding']} }},\n"
        f"    animations = {{ enabled = {b(s['animations'])} }},\n"
        "})\n"
    )


def save(s, config=CONFIG, symbols=XKB_SYMBOLS):
    """Check and store the settings, then write the Lua (Hyprland reloads by itself)."""
    s = dict(DEFAULTS, **{k: v for k, v in s.items() if k in DEFAULTS})
    s["kb_layout"] = check_layouts(s["kb_layout"], symbols)
    for k in SWITCHES:
        if not isinstance(s[k], bool):
            raise ValueError(f"{k} must be on or off")
    json_path, lua_path = paths(config)
    os.makedirs(os.path.dirname(json_path), exist_ok=True)
    for path, text in ((json_path, json.dumps(s, indent=1) + "\n"), (lua_path, to_lua(s))):
        with open(path + ".tmp", "w") as f:
            f.write(text)
        os.replace(path + ".tmp", path)
    return s
