#!/usr/bin/env python3
"""
Switch the desktop theme: bar, popups, notifications, window borders, lock
screen, wallpaper and kitty, all from one file in ~/.config/hypr/themes/ (see
the README there).

  theme.py list                 the themes you can pick
  theme.py current              the theme in use
  theme.py apply ID             switch to it (Hyprland reloads; the bar and popups restart)
  theme.py write [ID]           only write the generated files (install; no reload)
  theme.py bar                  only rewrite the bar colors (the Settings bar-strip switch)
  theme.py lock                 only rewrite the lock screen file (a Settings lock-screen picture)
"""
import json
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import fonts  # noqa: E402
import moment  # noqa: E402
import palette  # noqa: E402
import settings_store as store  # noqa: E402

CONFIG = os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config"))
HEADER = "generated by theme.py from ~/.config/hypr/themes/{id}.json: edits here are lost on the next switch"


def rgb(color):
    """ "#d3c6aa" -> "rgb(d3c6aa)" for Hyprland and hyprlock."""
    return f"rgb({color.lstrip('#')})"


def lua_str(s):
    """A Python string as a Lua string literal (JSON quoting is valid Lua here)."""
    return json.dumps(s, ensure_ascii=False)  # a JSON string is a valid Lua string here


def waybar_css(t):
    """waybar/colors/current.css: the colors as @define-color, for the bar and
    swaync, and the font rule both import (their own * rules carry no font).
    bar_strip and bar_strip_edge paint the strip behind the bar's pills: the
    theme's own colors, or transparent when Settings turns the strip off."""
    c = dict(t["colors"], grey1=t["colors"]["grey"])  # waybar's older name for grey
    strip = store.load()["bar_strip"]
    c["bar_strip"] = c["fg"] if strip else "alpha(@fg, 0)"
    c["bar_strip_edge"] = c["bar_edge"] if strip else "alpha(@bar_edge, 0)"
    return (f"/* {HEADER.format(**t)} */\n"
            + "".join(f"@define-color {k} {v};\n" for k, v in c.items())
            + fonts.css_rule())


def hypr_lua(t, wall):
    """hypr/themes/current.lua: what hyprland.lua reads (borders, shadows, GTK theme, wallpaper)."""
    c = t["colors"]
    fields = dict(
        id=t["id"],
        name=t["name"],
        gtk=t["gtk"],
        fg=rgb(c["fg"]),
        bg5=rgb(c["bg5"]),
        shadow=rgb(c["bar_edge"]),
        shadow_inactive=rgb(c["shadow_inactive"]),
        bg0=c["bg0"],
        wallpaper=wall or "",
    )
    body = "".join(f"    {k} = {lua_str(v)},\n" for k, v in fields.items())
    return f"-- {HEADER.format(**t)}\nreturn {{\n{body}}}\n"


def hyprlock_conf(t, wall, character=""):
    """hypr/hyprlock-colors.conf: $variables the lock screen sources. $character
    is the picture above the clock: empty draws none (LOCK-1)."""
    c = t["colors"]
    lines = [f"# {HEADER.format(**t)}"]
    lines += [f"${k} = {rgb(c[k])}" for k in ("fg", "bg0", "green", "yellow", "red", "edge_deep")]
    lines.append(f"$wallpaper = {wall or ''}")
    lines.append(f"$font = {fonts.families()[0]} Bold")
    lines.append(f"$character = {character or ''}")
    return "\n".join(lines) + "\n"


def lock_picture(theme_id, config=CONFIG):
    """GIF-4, LOCK-1: the GIF's flip-book link (gif_player.py --lock moves it) when
    the current theme has frames, else the theme's own picture, else ~/.face, else
    "" (no picture)."""
    if os.path.isfile(os.path.join(moment.gif_dir(), "current", "frames.json")):
        return os.path.join(moment.CACHE, "lock.png")
    own = palette.character(theme_id, os.path.join(config, "hypr", "characters"))
    face = os.path.expanduser("~/.face")
    return own or (face if os.path.isfile(face) else "")


def write_lock(config=CONFIG):
    """Only the lock screen file, for the current theme (LOCK-6): hyprlock reads it
    at the next lock, and no Hyprland file is written, so nothing reloads."""
    themes = os.path.join(config, "hypr", "themes")
    t = palette.theme(palette.current(themes), themes)
    wall = palette.wallpaper(os.path.join(config, "hypr", "wallpapers"), themes)
    write(os.path.join(config, "hypr", "hyprlock-colors.conf"), hyprlock_conf(t, wall, lock_picture(t["id"], config)))


# kitty's color names -> the theme's color roles (a full 16, like the Everforest
# file the installer puts in ~/.config/kitty/colors/)
KITTY = [
    ("background", "bg0"), ("foreground", "fg"),
    ("selection_foreground", "fg"), ("selection_background", "bg3"),
    ("cursor", "fg"), ("url_color", "blue"),
    ("color0", "bg2"), ("color1", "red"), ("color2", "green"), ("color3", "yellow"),
    ("color4", "blue"), ("color5", "purple"), ("color6", "aqua"), ("color7", "grey2"),
    ("color8", "grey0"), ("color9", "red_hover"), ("color10", "aqua"), ("color11", "yellow"),
    ("color12", "blue"), ("color13", "purple"), ("color14", "aqua"), ("color15", "fg"),
]


def kitty_conf(t):
    """kitty/colors/current.conf: the theme's colors and the desktop fonts.
    kitty watches its config files, so writing this recolors open windows."""
    c = t["colors"]
    lines = [f"# {HEADER.format(**t)}", fonts.kitty_font()]
    lines += [f"{name:<20} {c[role]}" for name, role in KITTY]
    return "\n".join(lines) + "\n"


def point_kitty_at_current(kitty_conf_path):
    """kitty.conf's `include colors/<name>.conf` -> the generated current.conf.
    A kitty.conf without such a line (or missing) is left alone."""
    try:
        with open(kitty_conf_path) as f:
            text = f.read()
    except OSError:
        return
    new = re.sub(r"^include colors/\S+\.conf$", "include colors/current.conf", text, flags=re.M)
    if new != text:
        write_in_place(kitty_conf_path, new)


def nudge_kitty():
    """Ask every running kitty to reload its config (colors included) with
    SIGUSR1, the documented way: its own file watching does not reliably pick
    up writes to the generated include file."""
    run(["pkill", "-USR1", "-x", "kitty"])


def write(path, text):
    """Replace the file in one step, so a reader never sees half of it."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path + ".tmp", "w") as f:
        f.write(text)
    os.replace(path + ".tmp", path)


def touch(path):
    """Write a file again in place, with the same content. Waybar's
    reload_style_on_change only reacts to an in-place write of its style file:
    not to a new mtime, and not to the @imported colors file being replaced."""
    try:
        with open(path) as f:
            text = f.read()
        with open(path, "w") as f:
            f.write(text)
    except OSError:
        pass  # not installed yet: nothing to nudge


def write_in_place(path, text):
    """Overwrite the file, keeping its inode. kitty watches the config files it
    loaded; a rename swaps the inode and running kitty windows would never see
    the new colors. A reader mid-write sees one torn reload at worst."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)


def refresh_moment(t, config):
    """The bar's GIF frames are decoration: a failure (no GdkPixbuf, a broken GIF)
    must not stop the theme switch."""
    try:
        moment.refresh(t, config)
    except Exception as e:  # noqa: BLE001 - any failure here only costs the sticker
        print(f"theme.py: no bar GIF for {t.get('id')}: {e}", file=sys.stderr)


def write_bar(config=CONFIG):
    """Only the bar colors, for the current theme: Waybar repaints in place, and no
    Hyprland file is written, so nothing reloads or restarts."""
    themes = os.path.join(config, "hypr", "themes")
    t = palette.theme(palette.current(themes), themes)
    write(os.path.join(config, "waybar", "colors", "current.css"), waybar_css(t))
    refresh_moment(t, config)  # before the touch, so the bar finds the frames
    touch(os.path.join(config, "waybar", "bar", "style.css"))


def write_all(theme_id, config=CONFIG):
    """Write every generated file for this theme. Returns the theme actually used."""
    themes = os.path.join(config, "hypr", "themes")
    t = palette.theme(theme_id, themes)
    wall = palette.wallpaper(os.path.join(config, "hypr", "wallpapers"), themes)
    write(os.path.join(config, "waybar", "colors", "current.css"), waybar_css(t))
    refresh_moment(t, config)  # before the touch, so the bar finds the frames
    touch(os.path.join(config, "waybar", "bar", "style.css"))  # Waybar reloads its CSS, no restart
    write(os.path.join(themes, "current.lua"), hypr_lua(t, wall))
    write(os.path.join(config, "hypr", "hyprlock-colors.conf"), hyprlock_conf(t, wall, lock_picture(t["id"], config)))
    kitty = os.path.join(config, "kitty")
    if os.path.isdir(kitty):  # not installed: nothing to recolor
        write_in_place(os.path.join(kitty, "colors", "current.conf"), kitty_conf(t))
        point_kitty_at_current(os.path.join(kitty, "kitty.conf"))
        nudge_kitty()
    write(os.path.join(themes, "current"), t["id"] + "\n")  # last: the others are ready
    return t


def run(argv):
    """A command's stdout, or "" when it is missing, fails or hangs."""
    try:
        return subprocess.run(argv, capture_output=True, text=True, timeout=5).stdout
    except (OSError, subprocess.TimeoutExpired):
        return ""


def reload():
    """Hyprland re-reads hyprland.lua, which restarts the bar, popups and wallpaper.

    Writing themes/current.lua already makes Hyprland reload by itself; a second
    `hyprctl reload` would restart everything twice. So only when autoreload is off."""
    try:
        autoreload_off = json.loads(run(["hyprctl", "-j", "getoption", "misc:disable_autoreload"]))["bool"]
    except (ValueError, KeyError, TypeError):
        autoreload_off = False  # can't tell: Hyprland's default is autoreload on
    if autoreload_off:
        run(["hyprctl", "reload"])
    run(["swaync-client", "--reload-css"])


def start_sticker(theme_id, config=CONFIG):
    """Show the pop-up sticker for the new theme, when its switch is on. It is
    decoration: it starts detached, and a failure to start never fails the switch (INV-3)."""
    if not store.load()["sticker_switch"]:
        return
    try:
        subprocess.Popen([os.path.join(config, "waybar", "scripts", "sticker.py"), theme_id],
                         start_new_session=True, stdin=subprocess.DEVNULL,
                         stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except OSError:
        pass


def main(argv):
    """The command line: list, current, apply, write."""
    cmd = argv[1] if len(argv) > 1 else "list"
    if cmd == "list":
        for tid, name, character in palette.available():
            print(f"{tid}\t{name}" + (f"\t{character}" if character else ""))
    elif cmd == "current":
        print(palette.current())
    elif cmd == "bar":
        write_bar()
    elif cmd == "lock":
        write_lock()
    elif cmd in ("apply", "write"):
        wanted = argv[2] if len(argv) > 2 else palette.current()
        if cmd == "apply" and palette.read(wanted) is None:
            print(f"no theme {wanted!r}; try: theme.py list", file=sys.stderr)
            return 1
        write_all(wanted)
        if cmd == "apply":
            reload()
            start_sticker(wanted)
    else:
        print((__doc__ or "").strip(), file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
