#!/usr/bin/env python3
"""
Switch the desktop theme: bar, popups, notifications, window borders, lock screen
and wallpaper, all from one file in ~/.config/hypr/themes/ (see the README there).

  theme.py list                 the themes you can pick
  theme.py current              the theme in use
  theme.py apply ID             switch to it (Hyprland reloads; the bar and popups restart)
  theme.py write [ID]           only write the generated files (install; no reload)
"""
import json
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import palette  # noqa: E402

CONFIG = os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config"))
HEADER = "generated by theme.py from ~/.config/hypr/themes/{id}.json: edits here are lost on the next switch"


def rgb(color):
    """ "#d3c6aa" -> "rgb(d3c6aa)" for Hyprland and hyprlock."""
    return f"rgb({color.lstrip('#')})"


def lua_str(s):
    """A Python string as a Lua string literal (JSON quoting is valid Lua here)."""
    return json.dumps(s, ensure_ascii=False)  # a JSON string is a valid Lua string here


def waybar_css(t):
    """waybar/colors/current.css: the colors as @define-color, for the bar and swaync."""
    c = dict(t["colors"], grey1=t["colors"]["grey"])  # waybar's older name for grey
    return f"/* {HEADER.format(**t)} */\n" + "".join(f"@define-color {k} {v};\n" for k, v in c.items())


def hypr_lua(t, wall):
    """hypr/themes/current.lua: what hyprland.lua reads (borders, shadows, GTK theme, wallpaper)."""
    c = t["colors"]
    fields = dict(
        id=t["id"],
        name=t["name"],
        gtk=t["gtk"],
        fg=rgb(c["fg"]),
        bg5=rgb(c["bg5"]),
        shadow=rgb(c["bar_edge"]),
        shadow_inactive=rgb(c["shadow_inactive"]),
        bg0=c["bg0"],
        wallpaper=wall or "",
    )
    body = "".join(f"    {k} = {lua_str(v)},\n" for k, v in fields.items())
    return f"-- {HEADER.format(**t)}\nreturn {{\n{body}}}\n"


def hyprlock_conf(t, wall):
    """hypr/hyprlock-colors.conf: $variables the lock screen sources."""
    c = t["colors"]
    lines = [f"# {HEADER.format(**t)}"]
    lines += [f"${k} = {rgb(c[k])}" for k in ("fg", "bg0", "green", "yellow", "red", "edge_deep")]
    lines.append(f"$wallpaper = {wall or ''}")
    return "\n".join(lines) + "\n"


def write(path, text):
    """Replace the file in one step, so a reader never sees half of it."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path + ".tmp", "w") as f:
        f.write(text)
    os.replace(path + ".tmp", path)


def write_all(theme_id, config=CONFIG):
    """Write every generated file for this theme. Returns the theme actually used."""
    themes = os.path.join(config, "hypr", "themes")
    t = palette.theme(theme_id, themes)
    wall = palette.wallpaper(t["id"], os.path.join(config, "hypr", "wallpapers"))
    write(os.path.join(config, "waybar", "colors", "current.css"), waybar_css(t))
    write(os.path.join(themes, "current.lua"), hypr_lua(t, wall))
    write(os.path.join(config, "hypr", "hyprlock-colors.conf"), hyprlock_conf(t, wall))
    write(os.path.join(themes, "current"), t["id"] + "\n")  # last: the others are ready
    return t


def run(argv):
    """A command's stdout, or "" when it is missing, fails or hangs."""
    try:
        return subprocess.run(argv, capture_output=True, text=True, timeout=5).stdout
    except (OSError, subprocess.TimeoutExpired):
        return ""


def reload():
    """Hyprland re-reads hyprland.lua, which restarts the bar, popups and wallpaper.

    Writing themes/current.lua already makes Hyprland reload by itself; a second
    `hyprctl reload` would restart everything twice. So only when autoreload is off."""
    try:
        autoreload_off = json.loads(run(["hyprctl", "-j", "getoption", "misc:disable_autoreload"]))["bool"]
    except (ValueError, KeyError, TypeError):
        autoreload_off = False  # can't tell: Hyprland's default is autoreload on
    if autoreload_off:
        run(["hyprctl", "reload"])
    run(["swaync-client", "--reload-css"])


def main(argv):
    """The command line: list, current, apply, write."""
    cmd = argv[1] if len(argv) > 1 else "list"
    if cmd == "list":
        for tid, name, character in palette.available():
            print(f"{tid}\t{name}" + (f"\t{character}" if character else ""))
    elif cmd == "current":
        print(palette.current())
    elif cmd in ("apply", "write"):
        wanted = argv[2] if len(argv) > 2 else palette.current()
        if cmd == "apply" and palette.read(wanted) is None:
            print(f"no theme {wanted!r}; try: theme.py list", file=sys.stderr)
            return 1
        write_all(wanted)
        if cmd == "apply":
            reload()
    else:
        print((__doc__ or "").strip(), file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
