#!/usr/bin/env bash
# Away-timer for Hyprland (drives hypridle) + Waybar box.
#   idle.sh apply                 write config & (re)start hypridle (run at login)
#   idle.sh set <mode> [minutes]  mode = sleep | lock | awake
#   idle.sh get                   prints "<mode> <minutes>"
#   idle.sh status                JSON for Waybar: the mode glyph only, the minutes on hover
#   idle.sh dim <percent> [battery]  dim the laptop screen (hypridle runs it); with
#                                 "battery", only on battery. Never makes it brighter
#   idle.sh undim                 the brightness from before the first dim, back
#
# sleep : after N min lock + screen off; then sleep once nothing is running
# lock  : after N min lock + screen off; never sleep (builds/terminals keep going)
# awake : nothing happens automatically
STATE="$HOME/.config/hypr/idle-state"
CONF="$HOME/.config/hypr/hypridle.conf"
SCRIPTS="$HOME/.config/waybar/scripts"
# the brightness before the first dim: the battery dim and the dim before the lock
# both run, and only the first one may save, or the screen comes back dimmed
DIMMED="${XDG_RUNTIME_DIR:-/tmp}/idle-dimmed"

MODE=sleep; MIN=5
if [[ -f "$STATE" ]]; then read -r m n < "$STATE"; fi
case "$m" in sleep|lock|awake) MODE=$m ;; esac
[[ "$n" =~ ^[0-9]+$ ]] && MIN=$n

save()    { mkdir -p "$(dirname "$STATE")"; echo "$MODE $MIN" > "$STATE"; }
refresh() { pkill -RTMIN+9 waybar 2>/dev/null; }
label()   { ((MIN >= 60)) && echo "$((MIN / 60))h" || echo "${MIN}m"; }
# Settings > Battery > Dim when idle, in minutes (0 = off)
battery_dim() {
  python3 -c 'import sys; sys.path.insert(0, sys.argv[1]); import settings_store as s; print(s.load()["battery_dim"])' \
    "$SCRIPTS" 2>/dev/null || echo 0
}
# the same rule as the bar's GIF: no charger at all (a desktop) counts as on AC.
# Only exit 3 means battery: a python error counts as AC too, so it never dims there.
# IDLE_POWER_ROOT is for the tests only.
on_ac() {
  python3 -c 'import os, sys; sys.path.insert(0, sys.argv[1]); import gif_player as g
sys.exit(0 if g.on_mains(os.environ.get("IDLE_POWER_ROOT", g.POWER_ROOT)) else 3)' "$SCRIPTS"
  (($? != 3))
}
# hypridle does not wait for a command, so an undim can start while a dim still runs:
# one at a time, or the undim finds nothing to restore and the screen stays dim
one_at_a_time() { exec 9>"$DIMMED.lock"; flock 9; }
dim() {
  one_at_a_time
  [[ "$2" == battery ]] && on_ac && return
  local now max target
  now=$(brightnessctl get) && max=$(brightnessctl max) || return
  target=$((max * $1 / 100))
  [[ -f "$DIMMED" ]] || echo "$now" > "$DIMMED"
  if ((now > target)); then brightnessctl -q set "$target"; fi
}
undim() {
  one_at_a_time
  [[ -f "$DIMMED" ]] || return 0
  brightnessctl -q set "$(<"$DIMMED")"
  rm -f "$DIMMED"
}

write_conf() {
  local away=$((MIN * 60))
  local dim=$(( away > 60 ? away - 30 : away - 15 ))
  # a non-number here would end the script after apply stopped hypridle (no lock, no sleep)
  local battery; battery=$(battery_dim); [[ "$battery" =~ ^[0-9]+$ ]] || battery=0
  battery=$((battery * 60))
  {
    cat <<CONF
# generated by ~/.config/hypr/scripts/idle.sh — use the bar's power box instead of editing
general {
    lock_cmd = ~/.config/hypr/scripts/lock.sh
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'; ~/.config/hypr/scripts/lid.sh check
    ignore_dbus_inhibit = false
    # suspend waits until the screen is locked: hypridle's auto mode (2) does that
    # only when lock_cmd names hyprlock, and ours is lock.sh
    inhibit_sleep = 3
}

listener {
    timeout = $dim
    on-timeout = ~/.config/hypr/scripts/idle.sh dim 10
    on-resume = ~/.config/hypr/scripts/idle.sh undim
}

listener {
    timeout = $away
    on-timeout = loginctl lock-session; sleep 2; hyprctl dispatch 'hl.dsp.dpms({ action = "off" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}
CONF
    if ((battery > 0)); then
      cat <<CONF

# Settings > Battery > Dim when idle: on battery only (30 %: the page's note says it too)
listener {
    timeout = $battery
    on-timeout = ~/.config/hypr/scripts/idle.sh dim 30 battery
    on-resume = ~/.config/hypr/scripts/idle.sh undim
}
CONF
    fi
    if [[ "$MODE" == sleep ]]; then
      cat <<CONF

# sleep only once nothing is running (builds, downloads, music…)
listener {
    timeout = $((away + 30))
    on-timeout = ~/.config/hypr/scripts/smart-sleep.sh
    on-resume = pkill -f smart-sleep.sh
}
CONF
    fi
  } > "$CONF"
}

apply() {
  pkill -x hypridle 2>/dev/null
  pkill -f smart-sleep.sh 2>/dev/null
  [[ "$MODE" == awake ]] && return
  write_conf
  (setsid hypridle -c "$CONF" >/dev/null 2>&1 &)
}

case "$1" in
  apply) apply ;;
  dim)   dim "$2" "$3" ;;
  undim) undim ;;
  get)   echo "$MODE $MIN" ;;
  set)
    case "$2" in sleep|lock|awake) MODE=$2 ;; esac
    [[ "$3" =~ ^[0-9]+$ ]] && MIN=$3
    save; apply; refresh ;;
  status|*)
    case "$MODE" in
      sleep) printf '{"text":"󰒲","class":"sleep","tooltip":"After %s away: lock, then sleep when nothing is running"}\n' "$(label)" ;;
      lock)  printf '{"text":"󰌾","class":"lock","tooltip":"After %s away: lock only — never sleeps"}\n' "$(label)" ;;
      awake) printf '{"text":"󰅶","class":"awake","tooltip":"Stay awake — nothing happens automatically"}\n' ;;
    esac ;;
esac
