#!/usr/bin/env bash
# Away-timer for Hyprland (drives hypridle) + Waybar box.
#   idle.sh apply                 write config & (re)start hypridle (run at login)
#   idle.sh set <mode> [minutes]  mode = sleep | lock | awake
#   idle.sh get                   prints "<mode> <minutes>"
#   idle.sh status                JSON for Waybar
#
# sleep : after N min lock + screen off; then sleep once nothing is running
# lock  : after N min lock + screen off; never sleep (builds/terminals keep going)
# awake : nothing happens automatically
STATE="$HOME/.config/hypr/idle-state"
CONF="$HOME/.config/hypr/hypridle.conf"

MODE=sleep; MIN=5
if [[ -f "$STATE" ]]; then read -r m n < "$STATE"; fi
case "$m" in sleep|lock|awake) MODE=$m ;; esac
[[ "$n" =~ ^[0-9]+$ ]] && MIN=$n

save()    { mkdir -p "$(dirname "$STATE")"; echo "$MODE $MIN" > "$STATE"; }
refresh() { pkill -RTMIN+9 waybar 2>/dev/null; }
label()   { ((MIN >= 60)) && echo "$((MIN / 60))h" || echo "${MIN}m"; }

write_conf() {
  local away=$((MIN * 60))
  local dim=$(( away > 60 ? away - 30 : away - 15 ))
  {
    cat <<CONF
# generated by ~/.config/hypr/scripts/idle.sh — use the bar's power box instead of editing
general {
    lock_cmd = pidof hyprlock || (hyprctl switchxkblayout all 0; hyprlock)
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'; ~/.config/hypr/scripts/lid.sh check
    ignore_dbus_inhibit = false
}

listener {
    timeout = $dim
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

listener {
    timeout = $away
    on-timeout = loginctl lock-session; sleep 2; hyprctl dispatch 'hl.dsp.dpms({ action = "off" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}
CONF
    if [[ "$MODE" == sleep ]]; then
      cat <<CONF

# sleep only once nothing is running (builds, downloads, music…)
listener {
    timeout = $((away + 30))
    on-timeout = ~/.config/hypr/scripts/smart-sleep.sh
    on-resume = pkill -f smart-sleep.sh
}
CONF
    fi
  } > "$CONF"
}

apply() {
  pkill -x hypridle 2>/dev/null
  pkill -f smart-sleep.sh 2>/dev/null
  [[ "$MODE" == awake ]] && return
  write_conf
  (setsid hypridle -c "$CONF" >/dev/null 2>&1 &)
}

case "$1" in
  apply) apply ;;
  get)   echo "$MODE $MIN" ;;
  set)
    case "$2" in sleep|lock|awake) MODE=$2 ;; esac
    [[ "$3" =~ ^[0-9]+$ ]] && MIN=$3
    save; apply; refresh ;;
  status|*)
    case "$MODE" in
      sleep) printf '{"text":"󰒲 %s","class":"sleep","tooltip":"After %s away: lock, then sleep when nothing is running"}\n' "$(label)" "$(label)" ;;
      lock)  printf '{"text":"󰌾 %s","class":"lock","tooltip":"After %s away: lock only — never sleeps"}\n' "$(label)" "$(label)" ;;
      awake) printf '{"text":"󰅶 awake","class":"awake","tooltip":"Stay awake — nothing happens automatically"}\n' ;;
    esac ;;
esac
